<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use App\Models\ProductSpecification;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'brand' => 'Apple',
                'category' => 'هواتف رائدة',
                'name' => 'iPhone 15 Pro Max',
                'slug' => 'iphone-15-pro-max',
                'short_description' => 'أكثر آيفون تطوراً على الإطلاق مع شريحة A17 Pro وتصميم تيتانيوم.',
                'description' => "آيفون 15 برو ماكس يتميز بتصميم تيتانيوم خفيف وقوي من الدرجة الفضائية مع ظهر زجاجي غير لامع. مبني للمتانة مع واجهة Ceramic Shield وحافة محيطية جديدة. زر الإجراءات يمنحك طريقة سريعة لإنجاز المهام. شريحة A17 Pro تقدم أداءً ثورياً للألعاب مع تتبع الأشعة ووحدة معالجة رسومات مخصصة.",
                'price' => 1199.00,
                'old_price' => 1299.00,
                'stock_quantity' => 25,
                'sku' => 'APL-IP15PM-256',
                'main_image' => 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-15-pro-max-1.jpg',
                'is_featured' => true,
                'is_active' => true,
                'specifications' => [
                    ['group' => 'Display', 'name' => 'Size', 'value' => '6.7 inches Super Retina XDR OLED'],
                    ['group' => 'Display', 'name' => 'Resolution', 'value' => '2796 x 1290 pixels'],
                    ['group' => 'Display', 'name' => 'Refresh Rate', 'value' => '120Hz ProMotion'],
                    ['group' => 'Performance', 'name' => 'Chipset', 'value' => 'Apple A17 Pro (3 nm)'],
                    ['group' => 'Performance', 'name' => 'RAM', 'value' => '8 GB'],
                    ['group' => 'Storage', 'name' => 'Internal', 'value' => '256 GB'],
                    ['group' => 'Camera', 'name' => 'Main', 'value' => '48 MP + 12 MP + 12 MP Triple Camera'],
                    ['group' => 'Camera', 'name' => 'Front', 'value' => '12 MP TrueDepth'],
                    ['group' => 'Battery', 'name' => 'Capacity', 'value' => '4422 mAh'],
                    ['group' => 'Battery', 'name' => 'Charging', 'value' => '27W wired, 15W MagSafe'],
                    ['group' => 'Connectivity', 'name' => 'Network', 'value' => '5G, Wi-Fi 6E, Bluetooth 5.3'],
                    ['group' => 'Build', 'name' => 'Material', 'value' => 'Titanium frame, Ceramic Shield front'],
                ],
            ],
            [
                'brand' => 'Apple',
                'category' => 'هواتف رائدة',
                'name' => 'iPhone 15 Pro',
                'slug' => 'iphone-15-pro',
                'short_description' => 'أداء احترافي في تصميم تيتانيوم مدمج مع شريحة A17 Pro.',
                'description' => "آيفون 15 برو يتميز بنفس شريحة A17 Pro وتصميم التيتانيوم ونظام الكاميرا الاحترافي مثل برو ماكس في حجم أكثر إدماجاً 6.1 بوصة. مثالي لمن يفضلون هاتفاً أصغر دون التنازل عن المزايا.",
                'price' => 999.00,
                'old_price' => 1099.00,
                'stock_quantity' => 30,
                'sku' => 'APL-IP15P-256',
                'main_image' => 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-15-pro-1.jpg',
                'is_featured' => true,
                'is_active' => true,
                'specifications' => [
                    ['group' => 'Display', 'name' => 'Size', 'value' => '6.1 inches Super Retina XDR OLED'],
                    ['group' => 'Display', 'name' => 'Resolution', 'value' => '2556 x 1179 pixels'],
                    ['group' => 'Display', 'name' => 'Refresh Rate', 'value' => '120Hz ProMotion'],
                    ['group' => 'Performance', 'name' => 'Chipset', 'value' => 'Apple A17 Pro (3 nm)'],
                    ['group' => 'Performance', 'name' => 'RAM', 'value' => '8 GB'],
                    ['group' => 'Storage', 'name' => 'Internal', 'value' => '256 GB'],
                    ['group' => 'Camera', 'name' => 'Main', 'value' => '48 MP + 12 MP + 12 MP Triple Camera'],
                    ['group' => 'Camera', 'name' => 'Front', 'value' => '12 MP TrueDepth'],
                    ['group' => 'Battery', 'name' => 'Capacity', 'value' => '3274 mAh'],
                    ['group' => 'Battery', 'name' => 'Charging', 'value' => '27W wired, 15W MagSafe'],
                ],
            ],
            [
                'brand' => 'Apple',
                'category' => 'هواتف رائدة',
                'name' => 'iPhone 15',
                'slug' => 'iphone-15',
                'short_description' => 'قوة هائلة مع Dynamic Island وكاميرا 48 ميجابيكسل.',
                'description' => "آيفون 15 يجلب Dynamic Island وكاميرا 48 ميجابيكسل ومنفذ USB-C إلى سلسلة آيفون القياسية. يتميز بشريحة A16 Bionic وعمر بطارية يدوم طوال اليوم.",
                'price' => 799.00,
                'old_price' => null,
                'stock_quantity' => 40,
                'sku' => 'APL-IP15-128',
                'main_image' => 'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-15-1.jpg',
                'is_featured' => false,
                'is_active' => true,
                'specifications' => [
                    ['group' => 'Display', 'name' => 'Size', 'value' => '6.1 inches Super Retina XDR OLED'],
                    ['group' => 'Display', 'name' => 'Resolution', 'value' => '2556 x 1179 pixels'],
                    ['group' => 'Performance', 'name' => 'Chipset', 'value' => 'Apple A16 Bionic (4 nm)'],
                    ['group' => 'Performance', 'name' => 'RAM', 'value' => '6 GB'],
                    ['group' => 'Storage', 'name' => 'Internal', 'value' => '128 GB'],
                    ['group' => 'Camera', 'name' => 'Main', 'value' => '48 MP + 12 MP Dual Camera'],
                    ['group' => 'Camera', 'name' => 'Front', 'value' => '12 MP TrueDepth'],
                    ['group' => 'Battery', 'name' => 'Capacity', 'value' => '3349 mAh'],
                ],
            ],
            [
                'brand' => 'Samsung',
                'category' => 'هواتف رائدة',
                'name' => 'Samsung Galaxy S24 Ultra',
                'slug' => 'samsung-galaxy-s24-ultra',
                'short_description' => 'جالكسي الأقوى مع قلم S Pen مدمج ومزايا الذكاء الاصطناعي.',
                'description' => "جالكسي S24 ألترا هو قمة تقنية سامسونج للهواتف الذكية. يتميز بإطار تيتانيوم وكاميرا 200 ميجابيكسل ومعالج Snapdragon 8 Gen 3 وGalaxy AI للترجمة الحية وتحرير الصور.",
                'price' => 1299.00,
                'old_price' => 1399.00,
                'stock_quantity' => 20,
                'sku' => 'SAM-S24U-256',
                'main_image' => 'https://images.samsung.com/is/image/samsung/assets/uk/mys24/smartswitch_S24ULTRA_mypage_vf.png',
                'is_featured' => true,
                'is_active' => true,
                'specifications' => [
                    ['group' => 'Display', 'name' => 'Size', 'value' => '6.8 inches Dynamic AMOLED 2X'],
                    ['group' => 'Display', 'name' => 'Resolution', 'value' => '3120 x 1440 pixels (QHD+)'],
                    ['group' => 'Display', 'name' => 'Refresh Rate', 'value' => '1-120Hz Adaptive'],
                    ['group' => 'Performance', 'name' => 'Chipset', 'value' => 'Snapdragon 8 Gen 3 (4 nm)'],
                    ['group' => 'Performance', 'name' => 'RAM', 'value' => '12 GB'],
                    ['group' => 'Storage', 'name' => 'Internal', 'value' => '256 GB'],
                    ['group' => 'Camera', 'name' => 'Main', 'value' => '200 MP + 12 MP + 10 MP + 50 MP Quad Camera'],
                    ['group' => 'Camera', 'name' => 'Front', 'value' => '12 MP'],
                    ['group' => 'Battery', 'name' => 'Capacity', 'value' => '5000 mAh'],
                    ['group' => 'Battery', 'name' => 'Charging', 'value' => '45W wired, 15W wireless'],
                    ['group' => 'Features', 'name' => 'S Pen', 'value' => 'Built-in S Pen included'],
                    ['group' => 'Features', 'name' => 'AI', 'value' => 'Galaxy AI with Live Translate'],
                ],
            ],
            [
                'brand' => 'Samsung',
                'category' => 'هواتف رائدة',
                'name' => 'Samsung Galaxy S24+',
                'slug' => 'samsung-galaxy-s24-plus',
                'short_description' => 'تجربة جالكسي بشاشة كبيرة مع قدرات الذكاء الاصطناعي.',
                'description' => "جالكسي S24+ يقدم شاشة أكبر 6.7 بوصة مع جميع مزايا Galaxy AI في تصميم أنيق.",
                'price' => 999.00,
                'old_price' => null,
                'stock_quantity' => 25,
                'sku' => 'SAM-S24P-256',
                'main_image' => 'https://www.telstra.com.au/content/dam/tcom/devices/mobile/mhdwhst-s24p/onyxblack/landscape-front.png',
                'is_featured' => false,
                'is_active' => true,
                'specifications' => [
                    ['group' => 'Display', 'name' => 'Size', 'value' => '6.7 inches Dynamic AMOLED 2X'],
                    ['group' => 'Display', 'name' => 'Resolution', 'value' => '3120 x 1440 pixels (QHD+)'],
                    ['group' => 'Performance', 'name' => 'Chipset', 'value' => 'Exynos 2400 (4 nm)'],
                    ['group' => 'Performance', 'name' => 'RAM', 'value' => '12 GB'],
                    ['group' => 'Storage', 'name' => 'Internal', 'value' => '256 GB'],
                    ['group' => 'Camera', 'name' => 'Main', 'value' => '50 MP + 12 MP + 10 MP Triple Camera'],
                    ['group' => 'Battery', 'name' => 'Capacity', 'value' => '4900 mAh'],
                ],
            ],
            [
                'brand' => 'Samsung',
                'category' => 'هواتف قابلة للطي',
                'name' => 'Samsung Galaxy Z Fold5',
                'slug' => 'samsung-galaxy-z-fold5',
                'short_description' => 'افتح عالمك مع الهاتف القابل للطي الأقوى.',
                'description' => "جالكسي Z Fold5 ينفتح على شاشة 7.6 بوصة شبيهة بالتابلت بينما يطوى إلى هاتف ذكي مدمج. مثالي للمهام المتعددة والإنتاجية.",
                'price' => 1799.00,
                'old_price' => 1899.00,
                'stock_quantity' => 15,
                'sku' => 'SAM-ZF5-256',
                'main_image' => 'https://cdn-ildjgbh.nitrocdn.com/RlnvamDNiSSsGtLjssyjFlJhcokxkkBK/assets/images/optimized/alm.care/wp-content/uploads/2024/09/Alm.care-fold5.jpg',
                'is_featured' => true,
                'is_active' => true,
                'specifications' => [
                    ['group' => 'Display', 'name' => 'Main', 'value' => '7.6 inches Dynamic AMOLED 2X'],
                    ['group' => 'Display', 'name' => 'Cover', 'value' => '6.2 inches Dynamic AMOLED 2X'],
                    ['group' => 'Display', 'name' => 'Refresh Rate', 'value' => '120Hz Adaptive'],
                    ['group' => 'Performance', 'name' => 'Chipset', 'value' => 'Snapdragon 8 Gen 2 (4 nm)'],
                    ['group' => 'Performance', 'name' => 'RAM', 'value' => '12 GB'],
                    ['group' => 'Storage', 'name' => 'Internal', 'value' => '256 GB'],
                    ['group' => 'Camera', 'name' => 'Main', 'value' => '50 MP + 12 MP + 10 MP Triple Camera'],
                    ['group' => 'Battery', 'name' => 'Capacity', 'value' => '4400 mAh'],
                    ['group' => 'Features', 'name' => 'Fold', 'value' => 'Flex Mode, Multi Window'],
                ],
            ],
            [
                'brand' => 'Samsung',
                'category' => 'هواتف قابلة للطي',
                'name' => 'Samsung Galaxy Z Flip5',
                'slug' => 'samsung-galaxy-z-flip5',
                'short_description' => 'هاتف قابل للطي مدمج بأناقة ومضمون.',
                'description' => "جالكسي Z Flip5 يتميز بشاشة غطاء Flex Window أكبر ويطوى ليناسب أي جيب. عبر عن نفسك بتصاميم فريدة.",
                'price' => 999.00,
                'old_price' => null,
                'stock_quantity' => 20,
                'sku' => 'SAM-ZFL5-256',
                'main_image' => 'https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_800,h_800/https://www.pricepoint.co.ke/wp-content/uploads/2025/03/Samsung-Galaxy-Z-Flip5-1-1.jpg',
                'is_featured' => false,
                'is_active' => true,
                'specifications' => [
                    ['group' => 'Display', 'name' => 'Main', 'value' => '6.7 inches Dynamic AMOLED 2X'],
                    ['group' => 'Display', 'name' => 'Cover', 'value' => '3.4 inches Super AMOLED'],
                    ['group' => 'Performance', 'name' => 'Chipset', 'value' => 'Snapdragon 8 Gen 2 (4 nm)'],
                    ['group' => 'Performance', 'name' => 'RAM', 'value' => '8 GB'],
                    ['group' => 'Storage', 'name' => 'Internal', 'value' => '256 GB'],
                    ['group' => 'Camera', 'name' => 'Main', 'value' => '12 MP + 12 MP Dual Camera'],
                    ['group' => 'Battery', 'name' => 'Capacity', 'value' => '3700 mAh'],
                ],
            ],
            [
                'brand' => 'Samsung',
                'category' => 'الفئة المتوسطة',
                'name' => 'Samsung Galaxy A54 5G',
                'slug' => 'samsung-galaxy-a54-5g',
                'short_description' => 'كاميرا وشاشة رائعة بسعر مذهل.',
                'description' => "جالكسي A54 5G يقدم ميزات متميزة تشمل كاميرا 50 ميجابكسل وشاشة Super AMOLED بمعدل 120Hz ومقاومة للماء IP67 بسعر الفئة المتوسطة.",
                'price' => 449.00,
                'old_price' => 499.00,
                'stock_quantity' => 50,
                'sku' => 'SAM-A54-128',
                'main_image' => 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=400&h=400&fit=crop',
                'is_featured' => false,
                'is_active' => true,
                'specifications' => [
                    ['group' => 'Display', 'name' => 'Size', 'value' => '6.4 inches Super AMOLED'],
                    ['group' => 'Display', 'name' => 'Resolution', 'value' => '2340 x 1080 pixels (FHD+)'],
                    ['group' => 'Display', 'name' => 'Refresh Rate', 'value' => '120Hz'],
                    ['group' => 'Performance', 'name' => 'Chipset', 'value' => 'Exynos 1380 (5 nm)'],
                    ['group' => 'Performance', 'name' => 'RAM', 'value' => '8 GB'],
                    ['group' => 'Storage', 'name' => 'Internal', 'value' => '128 GB'],
                    ['group' => 'Camera', 'name' => 'Main', 'value' => '50 MP + 12 MP + 5 MP Triple Camera'],
                    ['group' => 'Battery', 'name' => 'Capacity', 'value' => '5000 mAh'],
                    ['group' => 'Features', 'name' => 'Water Resistance', 'value' => 'IP67'],
                ],
            ],
            [
                'brand' => 'Xiaomi',
                'category' => 'هواتف رائدة',
                'name' => 'Xiaomi 14 Ultra',
                'slug' => 'xiaomi-14-ultra',
                'short_description' => 'نظام كاميرا Leica رباعية للتصوير الاحترافي.',
                'description' => "شاومي 14 ألترا يتميز بعدسات لايكا مع كاميرا رئيسية بفتحة عدسة متغيرة ومعالج سنابدراجون 8 الجيل الثالث وتقنية الشحن السريع 90 واط.",
                'price' => 1199.00,
                'old_price' => null,
                'stock_quantity' => 15,
                'sku' => 'XIA-14U-512',
                'main_image' => 'https://fdn2.gsmarena.com/vv/pics/xiaomi/xiaomi-14-ultra-1.jpg',
                'is_featured' => true,
                'is_active' => true,
                'specifications' => [
                    ['group' => 'Display', 'name' => 'Size', 'value' => '6.73 inches LTPO AMOLED'],
                    ['group' => 'Display', 'name' => 'Resolution', 'value' => '3200 x 1440 pixels (2K)'],
                    ['group' => 'Display', 'name' => 'Refresh Rate', 'value' => '1-120Hz LTPO'],
                    ['group' => 'Performance', 'name' => 'Chipset', 'value' => 'Snapdragon 8 Gen 3 (4 nm)'],
                    ['group' => 'Performance', 'name' => 'RAM', 'value' => '16 GB'],
                    ['group' => 'Storage', 'name' => 'Internal', 'value' => '512 GB'],
                    ['group' => 'Camera', 'name' => 'Main', 'value' => '50 MP Leica Quad Camera with Variable Aperture'],
                    ['group' => 'Camera', 'name' => 'Front', 'value' => '32 MP'],
                    ['group' => 'Battery', 'name' => 'Capacity', 'value' => '5000 mAh'],
                    ['group' => 'Battery', 'name' => 'Charging', 'value' => '90W wired, 80W wireless'],
                ],
            ],
            [
                'brand' => 'Xiaomi',
                'category' => 'الفئة المتوسطة',
                'name' => 'Xiaomi Redmi Note 13 Pro+ 5G',
                'slug' => 'xiaomi-redmi-note-13-pro-plus-5g',
                'short_description' => 'كاميرا 200 ميجابكسل وشحن 120 واط بسعر الفئة المتوسطة.',
                'description' => "ريدمي نوت 13 برو+ 5G يقدم كاميرا 200 ميجابكسل بمستوى الفئة الرائدة وشحن سريع 120 واط وشاشة AMOLED بمعدل 120Hz بقيمة مذهلة.",
                'price' => 399.00,
                'old_price' => 449.00,
                'stock_quantity' => 35,
                'sku' => 'XIA-RN13PP-256',
                'main_image' => 'https://fdn2.gsmarena.com/vv/pics/xiaomi/xiaomi-redmi-note-13-pro-plus-1.jpg',
                'is_featured' => false,
                'is_active' => true,
                'specifications' => [
                    ['group' => 'Display', 'name' => 'Size', 'value' => '6.67 inches AMOLED'],
                    ['group' => 'Display', 'name' => 'Resolution', 'value' => '2712 x 1220 pixels'],
                    ['group' => 'Display', 'name' => 'Refresh Rate', 'value' => '120Hz'],
                    ['group' => 'Performance', 'name' => 'Chipset', 'value' => 'MediaTek Dimensity 7200-Ultra'],
                    ['group' => 'Performance', 'name' => 'RAM', 'value' => '12 GB'],
                    ['group' => 'Storage', 'name' => 'Internal', 'value' => '256 GB'],
                    ['group' => 'Camera', 'name' => 'Main', 'value' => '200 MP + 8 MP + 2 MP Triple Camera'],
                    ['group' => 'Battery', 'name' => 'Capacity', 'value' => '5000 mAh'],
                    ['group' => 'Battery', 'name' => 'Charging', 'value' => '120W HyperCharge'],
                ],
            ],
            [
                'brand' => 'Xiaomi',
                'category' => 'هواتف اقتصادية',
                'name' => 'Xiaomi Redmi 13C',
                'slug' => 'xiaomi-redmi-13c',
                'short_description' => 'ملك الهواتف الاقتصادية بكاميرا 50 ميجابكسل وبطارية ضخمة.',
                'description' => "ريدمي 13C يقدم ميزات الهاتف الذكي الأساسية تشمل كاميرا 50 ميجابكسل وبطارية 5000 مللي أمبير وشاشة 90Hz بسعر لا يقاوم.",
                'price' => 149.00,
                'old_price' => null,
                'stock_quantity' => 60,
                'sku' => 'XIA-R13C-128',
                'main_image' => 'https://fdn2.gsmarena.com/vv/pics/xiaomi/xiaomi-redmi-13c-1.jpg',
                'is_featured' => false,
                'is_active' => true,
                'specifications' => [
                    ['group' => 'Display', 'name' => 'Size', 'value' => '6.74 inches IPS LCD'],
                    ['group' => 'Display', 'name' => 'Resolution', 'value' => '1600 x 720 pixels (HD+)'],
                    ['group' => 'Display', 'name' => 'Refresh Rate', 'value' => '90Hz'],
                    ['group' => 'Performance', 'name' => 'Chipset', 'value' => 'MediaTek Helio G85'],
                    ['group' => 'Performance', 'name' => 'RAM', 'value' => '4 GB'],
                    ['group' => 'Storage', 'name' => 'Internal', 'value' => '128 GB'],
                    ['group' => 'Camera', 'name' => 'Main', 'value' => '50 MP Dual Camera'],
                    ['group' => 'Battery', 'name' => 'Capacity', 'value' => '5000 mAh'],
                ],
            ],
            [
                'brand' => 'OnePlus',
                'category' => 'هواتف رائدة',
                'name' => 'OnePlus 12',
                'slug' => 'oneplus-12',
                'short_description' => 'قاتل الفئة الرائدة بكاميرا Hasselblad وشحن 100 واط.',
                'description' => "ون بلس 12 يتميز بمعالج سنابدراجون 8 الجيل الثالث ونظام كاميرا هاسيلبلاد وشحن SUPERVOOC بقوة 100 واط وشاشة 2K LTPO مذهلة.",
                'price' => 799.00,
                'old_price' => 899.00,
                'stock_quantity' => 25,
                'sku' => 'OP-12-256',
                'main_image' => 'https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-12-1.jpg',
                'is_featured' => true,
                'is_active' => true,
                'specifications' => [
                    ['group' => 'Display', 'name' => 'Size', 'value' => '6.82 inches LTPO AMOLED'],
                    ['group' => 'Display', 'name' => 'Resolution', 'value' => '3168 x 1440 pixels (2K)'],
                    ['group' => 'Display', 'name' => 'Refresh Rate', 'value' => '1-120Hz LTPO'],
                    ['group' => 'Performance', 'name' => 'Chipset', 'value' => 'Snapdragon 8 Gen 3 (4 nm)'],
                    ['group' => 'Performance', 'name' => 'RAM', 'value' => '12 GB'],
                    ['group' => 'Storage', 'name' => 'Internal', 'value' => '256 GB'],
                    ['group' => 'Camera', 'name' => 'Main', 'value' => '50 MP Hasselblad Triple Camera'],
                    ['group' => 'Battery', 'name' => 'Capacity', 'value' => '5400 mAh'],
                    ['group' => 'Battery', 'name' => 'Charging', 'value' => '100W SUPERVOOC, 50W wireless'],
                ],
            ],
            [
                'brand' => 'OnePlus',
                'category' => 'الفئة المتوسطة',
                'name' => 'OnePlus Nord 3 5G',
                'slug' => 'oneplus-nord-3-5g',
                'short_description' => 'أداء الفئة الرائدة بسعر الفئة المتوسطة.',
                'description' => "ون بلس نورد 3 5G يجلب معالج Dimensity 9000 الرائد وشحن 80 واط وكاميرات معايرة بتقنية هاسيلبلاد إلى فئة الهواتف المتوسطة.",
                'price' => 449.00,
                'old_price' => null,
                'stock_quantity' => 30,
                'sku' => 'OP-N3-256',
                'main_image' => 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&h=400&fit=crop',
                'is_featured' => false,
                'is_active' => true,
                'specifications' => [
                    ['group' => 'Display', 'name' => 'Size', 'value' => '6.74 inches Fluid AMOLED'],
                    ['group' => 'Display', 'name' => 'Resolution', 'value' => '2772 x 1240 pixels'],
                    ['group' => 'Display', 'name' => 'Refresh Rate', 'value' => '120Hz'],
                    ['group' => 'Performance', 'name' => 'Chipset', 'value' => 'MediaTek Dimensity 9000 (4 nm)'],
                    ['group' => 'Performance', 'name' => 'RAM', 'value' => '16 GB'],
                    ['group' => 'Storage', 'name' => 'Internal', 'value' => '256 GB'],
                    ['group' => 'Camera', 'name' => 'Main', 'value' => '50 MP + 8 MP + 2 MP Triple Camera'],
                    ['group' => 'Battery', 'name' => 'Capacity', 'value' => '5000 mAh'],
                    ['group' => 'Battery', 'name' => 'Charging', 'value' => '80W SUPERVOOC'],
                ],
            ],
            [
                'brand' => 'Google',
                'category' => 'هواتف رائدة',
                'name' => 'Google Pixel 8 Pro',
                'slug' => 'google-pixel-8-pro',
                'short_description' => 'أفضل ما في جوجل مع ميزات الذكاء الاصطناعي والكاميرا.',
                'description' => "بكسل 8 برو يتميز بمعالج Tensor G3 من جوجل وقدرات ذكاء اصطناعي متقدمة وأفضل كاميرا هاتف ذكي و7 سنوات من التحديثات.",
                'price' => 999.00,
                'old_price' => null,
                'stock_quantity' => 18,
                'sku' => 'GOO-P8P-256',
                'main_image' => 'https://fdn2.gsmarena.com/vv/pics/google/google-pixel-8-pro-1.jpg',
                'is_featured' => true,
                'is_active' => true,
                'specifications' => [
                    ['group' => 'Display', 'name' => 'Size', 'value' => '6.7 inches LTPO OLED'],
                    ['group' => 'Display', 'name' => 'Resolution', 'value' => '2992 x 1344 pixels'],
                    ['group' => 'Display', 'name' => 'Refresh Rate', 'value' => '1-120Hz LTPO'],
                    ['group' => 'Performance', 'name' => 'Chipset', 'value' => 'Google Tensor G3'],
                    ['group' => 'Performance', 'name' => 'RAM', 'value' => '12 GB'],
                    ['group' => 'Storage', 'name' => 'Internal', 'value' => '256 GB'],
                    ['group' => 'Camera', 'name' => 'Main', 'value' => '50 MP + 48 MP + 48 MP Triple Camera'],
                    ['group' => 'Camera', 'name' => 'Front', 'value' => '10.5 MP'],
                    ['group' => 'Battery', 'name' => 'Capacity', 'value' => '5050 mAh'],
                    ['group' => 'Battery', 'name' => 'Charging', 'value' => '30W wired, 23W wireless'],
                    ['group' => 'Software', 'name' => 'Updates', 'value' => '7 years of OS updates'],
                ],
            ],
            [
                'brand' => 'Google',
                'category' => 'هواتف الكاميرا',
                'name' => 'Google Pixel 8',
                'slug' => 'google-pixel-8',
                'short_description' => 'تجربة بكسل في تصميم مدمج.',
                'description' => "بكسل 8 يجلب نفس إمكانيات الكاميرا الممتازة وميزات الذكاء الاصطناعي كالنسخة برو في تصميم مدمج بشاشة 6.2 بوصة.",
                'price' => 699.00,
                'old_price' => null,
                'stock_quantity' => 22,
                'sku' => 'GOO-P8-128',
                'main_image' => 'https://fdn2.gsmarena.com/vv/pics/google/google-pixel-8-1.jpg',
                'is_featured' => false,
                'is_active' => true,
                'specifications' => [
                    ['group' => 'Display', 'name' => 'Size', 'value' => '6.2 inches OLED'],
                    ['group' => 'Display', 'name' => 'Resolution', 'value' => '2400 x 1080 pixels'],
                    ['group' => 'Display', 'name' => 'Refresh Rate', 'value' => '60-120Hz'],
                    ['group' => 'Performance', 'name' => 'Chipset', 'value' => 'Google Tensor G3'],
                    ['group' => 'Performance', 'name' => 'RAM', 'value' => '8 GB'],
                    ['group' => 'Storage', 'name' => 'Internal', 'value' => '128 GB'],
                    ['group' => 'Camera', 'name' => 'Main', 'value' => '50 MP + 12 MP Dual Camera'],
                    ['group' => 'Battery', 'name' => 'Capacity', 'value' => '4575 mAh'],
                ],
            ],
            [
                'brand' => 'OPPO',
                'category' => 'هواتف رائدة',
                'name' => 'OPPO Find X7 Ultra',
                'slug' => 'oppo-find-x7-ultra',
                'short_description' => 'نظام كاميرا بيريسكوب مزدوج للتصوير الفائق.',
                'description' => "أوبو فايند X7 ألترا يتميز بكاميرتي تيليفوتو بيريسكوب مزدوجتين مطورتين مع هاسيلبلاد لقدرات تقريب لا مثيل لها.",
                'price' => 1099.00,
                'old_price' => null,
                'stock_quantity' => 12,
                'sku' => 'OPP-X7U-512',
                'main_image' => 'https://fdn2.gsmarena.com/vv/pics/oppo/oppo-find-x7-ultra-1.jpg',
                'is_featured' => true,
                'is_active' => true,
                'specifications' => [
                    ['group' => 'Display', 'name' => 'Size', 'value' => '6.82 inches LTPO AMOLED'],
                    ['group' => 'Display', 'name' => 'Resolution', 'value' => '3168 x 1440 pixels'],
                    ['group' => 'Display', 'name' => 'Refresh Rate', 'value' => '1-120Hz LTPO'],
                    ['group' => 'Performance', 'name' => 'Chipset', 'value' => 'Snapdragon 8 Gen 3 (4 nm)'],
                    ['group' => 'Performance', 'name' => 'RAM', 'value' => '16 GB'],
                    ['group' => 'Storage', 'name' => 'Internal', 'value' => '512 GB'],
                    ['group' => 'Camera', 'name' => 'Main', 'value' => '50 MP Quad Camera with Dual Periscope'],
                    ['group' => 'Battery', 'name' => 'Capacity', 'value' => '5000 mAh'],
                    ['group' => 'Battery', 'name' => 'Charging', 'value' => '100W SUPERVOOC, 50W wireless'],
                ],
            ],
            [
                'brand' => 'OPPO',
                'category' => 'الفئة المتوسطة',
                'name' => 'OPPO Reno11 5G',
                'slug' => 'oppo-reno11-5g',
                'short_description' => 'خبير البورتريه بتصوير معزز بالذكاء الاصطناعي.',
                'description' => "أوبو رينو 11 5G يتفوق في تصوير البورتريه بنظام كاميرا معزز بالذكاء الاصطناعي وتصميم أنيق.",
                'price' => 449.00,
                'old_price' => null,
                'stock_quantity' => 28,
                'sku' => 'OPP-R11-256',
                'main_image' => 'https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=400&h=400&fit=crop',
                'is_featured' => false,
                'is_active' => true,
                'specifications' => [
                    ['group' => 'Display', 'name' => 'Size', 'value' => '6.7 inches AMOLED'],
                    ['group' => 'Display', 'name' => 'Resolution', 'value' => '2412 x 1080 pixels'],
                    ['group' => 'Display', 'name' => 'Refresh Rate', 'value' => '120Hz'],
                    ['group' => 'Performance', 'name' => 'Chipset', 'value' => 'MediaTek Dimensity 7050'],
                    ['group' => 'Performance', 'name' => 'RAM', 'value' => '12 GB'],
                    ['group' => 'Storage', 'name' => 'Internal', 'value' => '256 GB'],
                    ['group' => 'Camera', 'name' => 'Main', 'value' => '50 MP + 8 MP + 32 MP Triple Camera'],
                    ['group' => 'Battery', 'name' => 'Capacity', 'value' => '5000 mAh'],
                    ['group' => 'Battery', 'name' => 'Charging', 'value' => '67W SUPERVOOC'],
                ],
            ],
            [
                'brand' => 'Realme',
                'category' => 'هواتف الألعاب',
                'name' => 'Realme GT5 Pro',
                'slug' => 'realme-gt5-pro',
                'short_description' => 'وحش الألعاب بمعالج سنابدراجون 8 الجيل الثالث وشاشة 144Hz.',
                'description' => "ريلمي GT5 برو يقدم أداء ألعاب رائد بمعالج سنابدراجون 8 الجيل الثالث وشاشة 144Hz ونظام تبريد متقدم.",
                'price' => 649.00,
                'old_price' => 699.00,
                'stock_quantity' => 20,
                'sku' => 'RLM-GT5P-256',
                'main_image' => 'https://fdn2.gsmarena.com/vv/pics/realme/realme-gt5-pro-1.jpg',
                'is_featured' => true,
                'is_active' => true,
                'specifications' => [
                    ['group' => 'Display', 'name' => 'Size', 'value' => '6.78 inches LTPO AMOLED'],
                    ['group' => 'Display', 'name' => 'Resolution', 'value' => '2780 x 1264 pixels'],
                    ['group' => 'Display', 'name' => 'Refresh Rate', 'value' => '1-144Hz LTPO'],
                    ['group' => 'Performance', 'name' => 'Chipset', 'value' => 'Snapdragon 8 Gen 3 (4 nm)'],
                    ['group' => 'Performance', 'name' => 'RAM', 'value' => '12 GB'],
                    ['group' => 'Storage', 'name' => 'Internal', 'value' => '256 GB'],
                    ['group' => 'Camera', 'name' => 'Main', 'value' => '50 MP + 8 MP + 50 MP Triple Camera'],
                    ['group' => 'Battery', 'name' => 'Capacity', 'value' => '5400 mAh'],
                    ['group' => 'Battery', 'name' => 'Charging', 'value' => '100W SUPERVOOC'],
                    ['group' => 'Gaming', 'name' => 'Cooling', 'value' => 'Stainless Steel Vapor Chamber'],
                ],
            ],
            [
                'brand' => 'Realme',
                'category' => 'هواتف اقتصادية',
                'name' => 'Realme C55',
                'slug' => 'realme-c55',
                'short_description' => 'تصميم Dynamic Island بسعر اقتصادي.',
                'description' => "ريلمي C55 يجلب ميزة Mini Capsule الشبيهة بـ Dynamic Island إلى الفئة الاقتصادية مع كاميرا 64 ميجابكسل وشحن 33 واط.",
                'price' => 179.00,
                'old_price' => null,
                'stock_quantity' => 45,
                'sku' => 'RLM-C55-128',
                'main_image' => 'https://fdn2.gsmarena.com/vv/pics/realme/realme-c55-1.jpg',
                'is_featured' => false,
                'is_active' => true,
                'specifications' => [
                    ['group' => 'Display', 'name' => 'Size', 'value' => '6.72 inches IPS LCD'],
                    ['group' => 'Display', 'name' => 'Resolution', 'value' => '2400 x 1080 pixels (FHD+)'],
                    ['group' => 'Display', 'name' => 'Refresh Rate', 'value' => '90Hz'],
                    ['group' => 'Performance', 'name' => 'Chipset', 'value' => 'MediaTek Helio G88'],
                    ['group' => 'Performance', 'name' => 'RAM', 'value' => '6 GB'],
                    ['group' => 'Storage', 'name' => 'Internal', 'value' => '128 GB'],
                    ['group' => 'Camera', 'name' => 'Main', 'value' => '64 MP + 2 MP Dual Camera'],
                    ['group' => 'Battery', 'name' => 'Capacity', 'value' => '5000 mAh'],
                    ['group' => 'Battery', 'name' => 'Charging', 'value' => '33W SUPERVOOC'],
                ],
            ],
            [
                'brand' => 'Huawei',
                'category' => 'هواتف رائدة',
                'name' => 'Huawei P60 Pro',
                'slug' => 'huawei-p60-pro',
                'short_description' => 'نظام كاميرا Ultra Lighting بفتحة عدسة متغيرة.',
                'description' => "هواوي P60 برو يتميز بكاميرا Ultra Lighting بفتحة عدسة متغيرة وأداء استثنائي في الإضاءة المنخفضة وتصميم أنيق.",
                'price' => 1099.00,
                'old_price' => null,
                'stock_quantity' => 15,
                'sku' => 'HUA-P60P-256',
                'main_image' => 'https://fdn2.gsmarena.com/vv/pics/huawei/huawei-p60-pro-1.jpg',
                'is_featured' => true,
                'is_active' => true,
                'specifications' => [
                    ['group' => 'Display', 'name' => 'Size', 'value' => '6.67 inches LTPO OLED'],
                    ['group' => 'Display', 'name' => 'Resolution', 'value' => '2700 x 1220 pixels'],
                    ['group' => 'Display', 'name' => 'Refresh Rate', 'value' => '1-120Hz LTPO'],
                    ['group' => 'Performance', 'name' => 'Chipset', 'value' => 'Snapdragon 8+ Gen 1 (4 nm)'],
                    ['group' => 'Performance', 'name' => 'RAM', 'value' => '8 GB'],
                    ['group' => 'Storage', 'name' => 'Internal', 'value' => '256 GB'],
                    ['group' => 'Camera', 'name' => 'Main', 'value' => '48 MP Variable Aperture + 13 MP + 48 MP'],
                    ['group' => 'Camera', 'name' => 'Aperture', 'value' => 'f/1.4 - f/4.0 Variable'],
                    ['group' => 'Battery', 'name' => 'Capacity', 'value' => '4815 mAh'],
                    ['group' => 'Battery', 'name' => 'Charging', 'value' => '88W wired, 50W wireless'],
                ],
            ],
            [
                'brand' => 'Huawei',
                'category' => 'هواتف قابلة للطي',
                'name' => 'Huawei Mate X5',
                'slug' => 'huawei-mate-x5',
                'short_description' => 'هاتف قابل للطي فاخر بحماية زجاج Kunlun.',
                'description' => "هواوي ميت X5 يقدم تجربة قابلة للطي استثنائية بشاشتين وزجاج Kunlun واتصال الأقمار الصناعية.",
                'price' => 1999.00,
                'old_price' => null,
                'stock_quantity' => 8,
                'sku' => 'HUA-MX5-512',
                'main_image' => 'https://fdn2.gsmarena.com/vv/pics/huawei/huawei-mate-x5-1.jpg',
                'is_featured' => false,
                'is_active' => true,
                'specifications' => [
                    ['group' => 'Display', 'name' => 'Main', 'value' => '7.85 inches OLED'],
                    ['group' => 'Display', 'name' => 'Cover', 'value' => '6.4 inches OLED'],
                    ['group' => 'Display', 'name' => 'Refresh Rate', 'value' => '120Hz'],
                    ['group' => 'Performance', 'name' => 'Chipset', 'value' => 'Kirin 9000s'],
                    ['group' => 'Performance', 'name' => 'RAM', 'value' => '16 GB'],
                    ['group' => 'Storage', 'name' => 'Internal', 'value' => '512 GB'],
                    ['group' => 'Camera', 'name' => 'Main', 'value' => '50 MP + 13 MP + 12 MP Triple Camera'],
                    ['group' => 'Battery', 'name' => 'Capacity', 'value' => '5060 mAh'],
                    ['group' => 'Features', 'name' => 'Connectivity', 'value' => 'Satellite Communication'],
                ],
            ],
        ];

        foreach ($products as $productData) {
            $brand = Brand::where('name', $productData['brand'])->first();
            $category = Category::where('name', $productData['category'])->first();

            if ($brand && $category) {
                $specs = $productData['specifications'];
                unset($productData['specifications'], $productData['brand'], $productData['category']);

                $productData['brand_id'] = $brand->id;
                $productData['category_id'] = $category->id;

                $product = Product::create($productData);

                foreach ($specs as $index => $spec) {
                    ProductSpecification::create([
                        'product_id' => $product->id,
                        'spec_group' => $spec['group'],
                        'spec_name' => $spec['name'],
                        'spec_value' => $spec['value'],
                        'sort_order' => $index,
                    ]);
                }
            }
        }
    }
}